/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controller.DesignationController;
import controller.SchoolController;
import controller.SibilineTypeController;
import controller.StudentController;
import entity.Designation;
import entity.Parent;
import entity.School;
import entity.Sibiline;
import entity.Sibilinetype;
import entity.Student;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;
import javax.swing.table.DefaultTableModel;
import org.eclipse.persistence.exceptions.DatabaseException;

/**
 *
 * @author HP
 */
public class AddStudent extends javax.swing.JDialog {

    private DefaultTableModel dtm;
    private List<Sibilinetype> sibilinetypes;
    private List<School> allSchools;
    private List<Student> allStudents;
    private List<Designation> allDesignations;
    private boolean b;
    private String errMsg = "This rank already registered...";

    /**
     * Creates new form AddStudent
     */
    public AddStudent(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(null);
        dtm = (DefaultTableModel) tblSibiline.getModel();
        allStudents = StudentController.getAllStudent();
        loadSchools();
        loadDesignations();
    }

    private void loadSchools() {
        b = false;
        if (allSchools == null) {
            allSchools = SchoolController.getAllSchools();
        }
        cmbbxScl.removeAllItems();
        for (School s : allSchools) {
            cmbbxScl.addItem(s);
        }
        cmbbxScl.addItem("New");
        b = true;
    }

    private void loadDesignations() {
        b = false;
        if (allDesignations == null) {
            allDesignations = DesignationController.getAllDesignations();
        }
        cmbbxFatherDesig.removeAllItems();
        cmbbxMotherDesig.removeAllItems();
        for (Designation d : allDesignations) {
            cmbbxMotherDesig.addItem(d);
            cmbbxFatherDesig.addItem(d);
        }
        cmbbxFatherDesig.addItem("New");
        cmbbxMotherDesig.addItem("New");
        b = true;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        chbxMotherLive = new javax.swing.JCheckBox();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        chbxFatherLive = new javax.swing.JCheckBox();
        jLabel11 = new javax.swing.JLabel();
        cmbbxMotherDesig = new javax.swing.JComboBox();
        cmbbxFatherDesig = new javax.swing.JComboBox();
        jPanel3 = new javax.swing.JPanel();
        chBxElderBrother = new javax.swing.JCheckBox();
        chBxYoungerBro = new javax.swing.JCheckBox();
        chBxElderSis = new javax.swing.JCheckBox();
        chBxYoungerSis = new javax.swing.JCheckBox();
        spnrElBro = new javax.swing.JSpinner();
        spnrYngBro = new javax.swing.JSpinner();
        spnrYngSis = new javax.swing.JSpinner();
        spnrElSis = new javax.swing.JSpinner();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblSibiline = new javax.swing.JTable();
        btnGo = new javax.swing.JButton();
        btnSave = new javax.swing.JButton();
        btnCanel = new javax.swing.JButton();
        tfName = new javax.swing.JTextField();
        tfAddress = new javax.swing.JTextField();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jRadioButton3 = new javax.swing.JRadioButton();
        jRadioButton4 = new javax.swing.JRadioButton();
        spnrDRank = new javax.swing.JSpinner();
        tfTel = new javax.swing.JFormattedTextField();
        cmbbxScl = new javax.swing.JComboBox();
        jLabel12 = new javax.swing.JLabel();
        lblErrMsg = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("New Student");

        jLabel2.setText("Name ");

        jLabel3.setText("Address");

        jLabel4.setText("D. Rank");

        jLabel5.setText("Shy");

        jLabel6.setText("Telephone");

        jLabel7.setText("School");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Parent"));

        chbxMotherLive.setSelected(true);
        chbxMotherLive.setText("Live");
        chbxMotherLive.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chbxMotherLiveActionPerformed(evt);
            }
        });

        jLabel8.setText("Designation");

        jLabel9.setText("Mother");

        jLabel10.setText("Father");

        chbxFatherLive.setSelected(true);
        chbxFatherLive.setText("Live");
        chbxFatherLive.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chbxFatherLiveActionPerformed(evt);
            }
        });

        jLabel11.setText("Designation");

        cmbbxMotherDesig.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "New" }));
        cmbbxMotherDesig.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbbxMotherDesigActionPerformed(evt);
            }
        });

        cmbbxFatherDesig.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbbxFatherDesigActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addGap(18, 18, 18)
                        .addComponent(chbxMotherLive))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cmbbxMotherDesig, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cmbbxFatherDesig, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addGap(18, 18, 18)
                        .addComponent(chbxFatherLive)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(jLabel10)
                    .addComponent(chbxMotherLive)
                    .addComponent(chbxFatherLive))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jLabel11)
                    .addComponent(cmbbxMotherDesig, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmbbxFatherDesig, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Sibiline"));

        chBxElderBrother.setText("Elder Brother");
        chBxElderBrother.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chBxElderBrotherActionPerformed(evt);
            }
        });

        chBxYoungerBro.setText("Younger Brother");
        chBxYoungerBro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chBxYoungerBroActionPerformed(evt);
            }
        });

        chBxElderSis.setText("Elder Sister");
        chBxElderSis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chBxElderSisActionPerformed(evt);
            }
        });

        chBxYoungerSis.setText("Younger Sister");
        chBxYoungerSis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chBxYoungerSisActionPerformed(evt);
            }
        });

        spnrElBro.setModel(new javax.swing.SpinnerNumberModel(Integer.valueOf(1), Integer.valueOf(1), null, Integer.valueOf(1)));
        spnrElBro.setEnabled(false);
        spnrElBro.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                spnrElBroStateChanged(evt);
            }
        });

        spnrYngBro.setModel(new javax.swing.SpinnerNumberModel(Integer.valueOf(1), Integer.valueOf(1), null, Integer.valueOf(1)));
        spnrYngBro.setEnabled(false);

        spnrYngSis.setModel(new javax.swing.SpinnerNumberModel(Integer.valueOf(1), Integer.valueOf(1), null, Integer.valueOf(1)));
        spnrYngSis.setEnabled(false);

        spnrElSis.setModel(new javax.swing.SpinnerNumberModel(Integer.valueOf(1), Integer.valueOf(1), null, Integer.valueOf(1)));
        spnrElSis.setEnabled(false);

        tblSibiline.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Sibiline", "Doing What"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblSibiline.setRowHeight(20);
        jScrollPane1.setViewportView(tblSibiline);

        btnGo.setText("GO");
        btnGo.setEnabled(false);
        btnGo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(chBxElderBrother)
                            .addComponent(chBxYoungerBro))
                        .addGap(26, 26, 26)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(spnrYngBro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(spnrElBro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(84, 84, 84)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(chBxElderSis)
                                .addGap(43, 43, 43)
                                .addComponent(spnrElSis, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(chBxYoungerSis)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(spnrYngSis, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnGo)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(chBxElderBrother)
                            .addComponent(spnrElBro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(chBxYoungerBro)
                            .addComponent(spnrYngBro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(chBxElderSis)
                            .addComponent(spnrElSis, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(chBxYoungerSis)
                            .addComponent(spnrYngSis, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnGo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        btnSave.setText("Save");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        btnCanel.setText("Cancel");
        btnCanel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCanelActionPerformed(evt);
            }
        });

        tfName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfNameActionPerformed(evt);
            }
        });

        tfAddress.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfAddressActionPerformed(evt);
            }
        });

        buttonGroup1.add(jRadioButton1);
        jRadioButton1.setSelected(true);
        jRadioButton1.setText("1 st");
        jRadioButton1.setActionCommand("1");
        jRadioButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton1ActionPerformed(evt);
            }
        });

        buttonGroup1.add(jRadioButton2);
        jRadioButton2.setText("2 nd");
        jRadioButton2.setActionCommand("2");

        buttonGroup1.add(jRadioButton3);
        jRadioButton3.setText("3 rd");
        jRadioButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton3ActionPerformed(evt);
            }
        });

        buttonGroup1.add(jRadioButton4);
        jRadioButton4.setText("4 th");
        jRadioButton4.setActionCommand("4");

        spnrDRank.setModel(new javax.swing.SpinnerNumberModel(Integer.valueOf(60), Integer.valueOf(50), null, Integer.valueOf(1)));
        spnrDRank.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                spnrDRankStateChanged(evt);
            }
        });

        try {
            tfTel.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("0##-#######")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        cmbbxScl.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbbxSclActionPerformed(evt);
            }
        });

        lblErrMsg.setFont(new java.awt.Font("Tahoma", 2, 11)); // NOI18N
        lblErrMsg.setForeground(new java.awt.Color(204, 0, 0));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(189, 189, 189)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel7))
                                .addGap(32, 32, 32)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(tfAddress, javax.swing.GroupLayout.PREFERRED_SIZE, 362, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(tfName, javax.swing.GroupLayout.PREFERRED_SIZE, 362, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(spnrDRank, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(lblErrMsg, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(tfTel, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(jRadioButton1)
                                            .addGap(18, 18, 18)
                                            .addComponent(jRadioButton2)
                                            .addGap(18, 18, 18)
                                            .addComponent(jRadioButton3)
                                            .addGap(18, 18, 18)
                                            .addComponent(jRadioButton4)))
                                    .addComponent(cmbbxScl, javax.swing.GroupLayout.PREFERRED_SIZE, 341, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(124, 124, 124)
                                .addComponent(btnSave, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnCanel, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(14, 14, 14)))))
                .addContainerGap(15, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(tfName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(tfAddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(spnrDRank, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblErrMsg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jRadioButton1)
                    .addComponent(jRadioButton2)
                    .addComponent(jRadioButton3)
                    .addComponent(jRadioButton4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(tfTel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(cmbbxScl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnSave)
                        .addComponent(btnCanel)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void chBxYoungerBroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chBxYoungerBroActionPerformed
        spnrYngBro.setEnabled(chBxYoungerBro.isSelected());
        goBtnEnable();
    }//GEN-LAST:event_chBxYoungerBroActionPerformed

    private void chBxYoungerSisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chBxYoungerSisActionPerformed
        spnrYngSis.setEnabled(chBxYoungerSis.isSelected());
        goBtnEnable();
    }//GEN-LAST:event_chBxYoungerSisActionPerformed

    private void jRadioButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton1ActionPerformed

    private void tfNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfNameActionPerformed
        tfAddress.requestFocus();
    }//GEN-LAST:event_tfNameActionPerformed

    private void tfAddressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfAddressActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfAddressActionPerformed

    private void chbxMotherLiveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chbxMotherLiveActionPerformed

        cmbbxMotherDesig.setEnabled(chbxMotherLive.isSelected());

    }//GEN-LAST:event_chbxMotherLiveActionPerformed

    private void chbxFatherLiveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chbxFatherLiveActionPerformed
        cmbbxFatherDesig.setEnabled(chbxFatherLive.isSelected());
    }//GEN-LAST:event_chbxFatherLiveActionPerformed

    private void spnrElBroStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_spnrElBroStateChanged

    }//GEN-LAST:event_spnrElBroStateChanged

    private void chBxElderBrotherActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chBxElderBrotherActionPerformed
        spnrElBro.setEnabled(chBxElderBrother.isSelected());
        goBtnEnable();
    }//GEN-LAST:event_chBxElderBrotherActionPerformed

    private void chBxElderSisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chBxElderSisActionPerformed
        spnrElSis.setEnabled(chBxElderSis.isSelected());
        goBtnEnable();
    }//GEN-LAST:event_chBxElderSisActionPerformed

    private void btnGoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGoActionPerformed
        if (chBxElderBrother.isSelected()) {
            for (int i = 1; i <= (Integer) spnrElBro.getValue(); i++) {
                dtm.addRow(new String[]{"Elder Brother : " + i, ""});
            }
        }

        if (chBxElderSis.isSelected()) {
            for (int i = 1; i <= (Integer) spnrElSis.getValue(); i++) {
                dtm.addRow(new String[]{"Elder Sister : " + i, ""});
            }
        }

        if (chBxYoungerBro.isSelected()) {
            for (int i = 1; i <= (Integer) spnrYngBro.getValue(); i++) {
                dtm.addRow(new String[]{"Younger Brother : " + i, ""});
            }
        }

        if (chBxYoungerSis.isSelected()) {
            for (int i = 1; i <= (Integer) spnrYngSis.getValue(); i++) {
                dtm.addRow(new String[]{"Younger Sister : " + i, ""});
            }
        }


    }//GEN-LAST:event_btnGoActionPerformed

    private void cmbbxMotherDesigActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbbxMotherDesigActionPerformed
        Object selectedItem = cmbbxMotherDesig.getSelectedItem();
        if (selectedItem != null && selectedItem.toString().equals("New") && b) {
            String newDesignation = JOptionPane.showInputDialog("New Designation");
            cmbbxMotherDesig.removeItem("New");
            cmbbxFatherDesig.removeItem("New");
            Designation designation = new Designation(newDesignation);
            // cmbbxMotherDesig.insertItemAt(newDesignation, cmbbxFatherDesig.getItemCount() - 1);
            DesignationController.newDesignation(designation);
            designation = DesignationController.getDesignationByName(newDesignation);
            cmbbxMotherDesig.addItem(designation);
            cmbbxFatherDesig.addItem(designation);

            cmbbxMotherDesig.addItem("New");
            cmbbxFatherDesig.addItem("New");
            cmbbxMotherDesig.setSelectedItem(designation);
        }
    }//GEN-LAST:event_cmbbxMotherDesigActionPerformed

    private void cmbbxFatherDesigActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbbxFatherDesigActionPerformed
        Object selectedItem = cmbbxFatherDesig.getSelectedItem();
        if (selectedItem != null && selectedItem.toString().equals("New") && b) {
            String newDesignation = JOptionPane.showInputDialog("New Designation");
            cmbbxMotherDesig.removeItem("New");
            cmbbxFatherDesig.removeItem("New");
            Designation designation = new Designation(newDesignation);
            // cmbbxMotherDesig.insertItemAt(newDesignation, cmbbxFatherDesig.getItemCount() - 1);
            DesignationController.newDesignation(designation);
            designation = DesignationController.getDesignationByName(newDesignation);
            cmbbxFatherDesig.addItem(designation);
            cmbbxMotherDesig.addItem(designation);
            cmbbxMotherDesig.addItem("New");
            cmbbxFatherDesig.addItem("New");
            cmbbxFatherDesig.setSelectedItem(designation);
        }
    }//GEN-LAST:event_cmbbxFatherDesigActionPerformed

    private void cmbbxSclActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbbxSclActionPerformed
        Object selectedItem = cmbbxScl.getSelectedItem();
        if (selectedItem != null && selectedItem.toString().equals("New") && b) {
            String newScl = JOptionPane.showInputDialog("New School");
            cmbbxScl.removeItem("New");
            School school = new School(newScl);
            // cmbbxMotherDesig.insertItemAt(newDesignation, cmbbxFatherDesig.getItemCount() - 1);
            SchoolController.addNewSchool(school);
            school = SchoolController.findForName(newScl);
            cmbbxScl.addItem(school);
            cmbbxScl.addItem("New");
            cmbbxScl.setSelectedItem(school);
        }
    }//GEN-LAST:event_cmbbxSclActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        String name = tfName.getText();
        String address = tfAddress.getText();
        String tel = tfTel.getText();
        int rank = (Integer) spnrDRank.getValue();
        School school = (School) cmbbxScl.getSelectedItem();
        int shy = Integer.parseInt(buttonGroup1.getSelection().getActionCommand());

        Parent mother = null;
        Parent father = null;
        List<Parent> parents = new ArrayList();

        List<Sibiline> sibilines = new ArrayList<>();

        Student student = new Student(rank, name, address, shy, tel, parents, school, sibilines);
        if (chbxMotherLive.isSelected()) {
            Designation designation = (Designation) cmbbxMotherDesig.getSelectedItem();
            mother = new Parent("Mother", designation, student);
            parents.add(mother);
        }
        if (chbxFatherLive.isSelected()) {
            Designation designation = (Designation) cmbbxFatherDesig.getSelectedItem();
            father = new Parent("Father", designation, student);
            parents.add(father);
        }
        for (int i = 0; i < dtm.getRowCount(); i++) {

            String type = (String) dtm.getValueAt(i, 0);
            if (sibilinetypes == null) {
                sibilinetypes = SibilineTypeController.getAllSibilinetypes();
            }
            String desc = (String) dtm.getValueAt(i, 1);
            if (type.contains("Elder Brother")) {
                sibilines.add(new Sibiline(desc, sibilinetypes.get(0), student));
            } else if (type.contains("Elder Sister")) {
                sibilines.add(new Sibiline(desc, sibilinetypes.get(1), student));
            } else if (type.contains("Younger Brother")) {
                sibilines.add(new Sibiline(desc, sibilinetypes.get(2), student));
            } else {
                sibilines.add(new Sibiline(desc, sibilinetypes.get(3), student));
            }
        }
        try {
            System.out.println(school);
            StudentController.addStudent(student);
            
            new Thread() {
                @Override
                public void run() {
                    jLabel12.setText("Saved...");
                    try {
                        Thread.sleep(1500);
                    } catch (InterruptedException ex) {
                        Logger.getLogger(AddStudent.class.getName()).log(Level.SEVERE, null, ex);
                    }
                    jLabel12.setText("");
                }
            }.start();
            clear();
        } catch (DatabaseException e) {
            if (e.getMessage().contains("Duplicate entry")) {
                JOptionPane.showMessageDialog(this, "This Rank is Already registerd...", "", JOptionPane.ERROR_MESSAGE);
            }
        }
        // JOptionPane.showMessageDialog(this, "Saved...");

    }//GEN-LAST:event_btnSaveActionPerformed

    private void jRadioButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton3ActionPerformed

    private void btnCanelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCanelActionPerformed
        dispose();
    }//GEN-LAST:event_btnCanelActionPerformed

    private void spnrDRankStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_spnrDRankStateChanged
        
        int val = (int) spnrDRank.getValue();
//        boolean exist = false;
        for (Student s : allStudents) {
            if (s.getRank() == val) {
                lblErrMsg.setText(errMsg);
                break;
            } else {
                lblErrMsg.setText("");
            }
        }
        
    }//GEN-LAST:event_spnrDRankStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        try {
            /* Set the Nimbus look and feel */
            UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(AddStudent.class.getName()).log(Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            Logger.getLogger(AddStudent.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            Logger.getLogger(AddStudent.class.getName()).log(Level.SEVERE, null, ex);
        } catch (UnsupportedLookAndFeelException ex) {
            Logger.getLogger(AddStudent.class.getName()).log(Level.SEVERE, null, ex);
        }

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                AddStudent dialog = new AddStudent(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCanel;
    private javax.swing.JButton btnGo;
    private javax.swing.JButton btnSave;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JCheckBox chBxElderBrother;
    private javax.swing.JCheckBox chBxElderSis;
    private javax.swing.JCheckBox chBxYoungerBro;
    private javax.swing.JCheckBox chBxYoungerSis;
    private javax.swing.JCheckBox chbxFatherLive;
    private javax.swing.JCheckBox chbxMotherLive;
    private javax.swing.JComboBox cmbbxFatherDesig;
    private javax.swing.JComboBox cmbbxMotherDesig;
    private javax.swing.JComboBox cmbbxScl;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JRadioButton jRadioButton4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblErrMsg;
    private javax.swing.JSpinner spnrDRank;
    private javax.swing.JSpinner spnrElBro;
    private javax.swing.JSpinner spnrElSis;
    private javax.swing.JSpinner spnrYngBro;
    private javax.swing.JSpinner spnrYngSis;
    private javax.swing.JTable tblSibiline;
    private javax.swing.JTextField tfAddress;
    private javax.swing.JTextField tfName;
    private javax.swing.JFormattedTextField tfTel;
    // End of variables declaration//GEN-END:variables

    private void goBtnEnable(){
        btnGo.setEnabled(chBxElderBrother.isSelected() || chBxElderSis.isSelected() || chBxYoungerBro.isSelected() || chBxYoungerSis.isSelected());
    }
    private void clear(){
        tfName.setText("");
        tfAddress.setText("");
        tfTel.setText("");
        
        int rowCount = dtm.getRowCount();
        for (int i = 0; i < rowCount; i++) {
            dtm.removeRow(0);
        }
        
        chBxElderBrother.setSelected(false);
        chBxElderSis.setSelected(false);
        chBxYoungerBro.setSelected(false);
        chBxYoungerSis.setSelected(false);
        
        spnrElBro.setValue(1);
        spnrElSis.setValue(1);
        spnrYngBro.setValue(1);
        spnrYngSis.setValue(1);
        
    }
}
